spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 96dc2f01-6f5b-45c6-ab81-b164ddbacaae
  config:
    import:
      - nacos:datasource.yml?group=dev
      - nacos:mybatis.yml?group=dev
      - nacos:other.yml?group=dev
      - nacos:alipay.yml?group=dev

  application:
    name: gulimall-order