spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1484d838-c821-4a73-8ee9-6291d08a8155
  config:
    import:
      - nacos:datasource.yml?group=dev
      - nacos:mybatis.yml?group=dev
      - nacos:other.yml?group=dev

  application:
    name: gulimall-ware